In [3706]:
import numpy as np

In [3707]:
A=np.array([
    [1,1,2],
    [3,5,8]
])

In [3708]:
B=np.array([
    [2,3,5],
    [7,11,13]
])

In [3709]:
print (A+B)

[[ 3  4  7]
 [10 16 21]]


In [3710]:
A=np.array([
    [1,2],
    [0,1]
])

In [3711]:
B=np.array([
    [0,2],
])

In [3712]:
print ("A*B=",A*B)

A*B= [[0 4]
 [0 2]]


In [3713]:
# Lesson 2 elimination with matrices
# suppose you start with the following array
# x+2y+z=2
# 3x+8y+z=12
# 4y+z=2
# note the array of coefficients is called A
# note the last column is also called b

In [3714]:
A=np.array([
    [1,2,1],
    [3,8,1],
    [0,4,1]
])

In [3715]:
Ab=np.array([
    [1,2,1,2],
    [3,8,1,12],
    [0,4,1,2]
])

In [3716]:
# eliminate the x
# find the first x coefficient
xcoef1=Ab[0,0]

In [3717]:
print(xcoef1)

1


In [3718]:
# first make the first row xcoef and the second equal
# by multiplying the first row by something
# so find the multiple...
xmultiple=Ab[1,0]/Ab[0,0]

In [3719]:
print(xmultiple)

3.0


In [3720]:
# ...and then multiply first row by it
row1=Ab[0,0:4]
row2=Ab[1,0:4]
row3=Ab[2,0:4]
xrow1=xmultiple*row1
print (xrow1)

[ 3.  6.  3.  6.]


In [3721]:
# ...and then subtract first row from the second
newrow2=row2-xrow1
print(newrow2)

[ 0.  2. -2.  6.]


In [3722]:
# ...now you have your new matrix
A2=np.array([
    row1,newrow2,row3
])
print (A2)

[[ 1.  2.  1.  2.]
 [ 0.  2. -2.  6.]
 [ 0.  4.  1.  2.]]


In [3723]:
# you would normally need to do the same thing 
# to get a zero for x in the third row but in this case
# it is already zero

In [3724]:
# now we will "zero out" the y in the third row by finding the required multiple of second
ymultiple=A2[2,1]/A2[1,1]
print (ymultiple)

2.0


In [3725]:
# ...and then multiplying second row by it
row1=A2[0,0:4]
row2=A2[1,0:4]
row3=A2[2,0:4]
print(row1)
print(row2)
print(row3)

[ 1.  2.  1.  2.]
[ 0.  2. -2.  6.]
[ 0.  4.  1.  2.]


In [3726]:
yrow2=ymultiple*row2
print (yrow2)

[  0.   4.  -4.  12.]


In [3727]:
# ...and then subtracting second row from the third
newrow3=row3-yrow2
print(newrow3)

[  0.   0.   5. -10.]


In [3728]:
# ...now you have your new matrix
# note that the new x, y, z array below is also called U
# note that the last column is also called c
A3=np.array([
    row1,row2,newrow3
])
print(A3)

[[  1.   2.   1.   2.]
 [  0.   2.  -2.   6.]
 [  0.   0.   5. -10.]]


In [3729]:
# now we have the three pivots
pivots=np.array([
    A3[0,0],A3[1,1],A3[2,2]
])
print (pivots)

[ 1.  2.  5.]


In [3730]:
# determinant of the matrix
determinant=pivots[0]*pivots[1]*pivots[2]
print(determinant)

10.0


In [3731]:
# we can also BACK SUBSTITUTE to find our answer
# solve for z first
z=A3[2,3]/A3[2,2]
print (z)

-2.0


In [3732]:
# solve for y next
y=(A3[1,3]-A3[1,2]*z)/A3[1,1]
print(y)

1.0


In [3733]:
# solve for x last
x=(A3[0,3]-A3[0,2]*z-A3[0,1]*y)/A3[0,0]
print(x)

2.0


In [3734]:
# identity matrix
# note we have switched to "np.matrix" from "array"
# the reason is that matrix multiplication acts differently
I=np.matrix([
    [1,0,0],
    [0,1,0],
    [0,0,1]
])
print(I)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [3735]:
# show that identity matrix times a matrix gives you that
# there seems a discrepancy here to me vs what he says in lecture
# doesn't give you the same matrix
print(I)
print(A)
print(I*A)

[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[1 2 1]
 [3 8 1]
 [0 4 1]]
[[1 2 1]
 [3 8 1]
 [0 4 1]]


In [3736]:
# let's try something smaller to get a feel...
# ...a 2x2 multiplication
littleI=np.matrix([
    [1,0],
    [0,1]
])
littleA=np.array([
    [3,4],
    [5,6]
])

In [3737]:
print(littleI)
print(littleA)

[[1 0]
 [0 1]]
[[3 4]
 [5 6]]


In [3738]:
print(littleI*littleA)

[[3 4]
 [5 6]]


In [3739]:
print(littleA*littleI)

[[3 4]
 [5 6]]


In [3740]:
smallerI=np.matrix([1,1])
print(smallerI)

[[1 1]]


In [3741]:
print(smallerI*littleA)

[[ 8 10]]


In [3742]:
# now we want to see our elimination approach
# using matrix multiplication

In [3743]:
# matrix to multiply against A
# first based on the calc above
# used to isolate x
# the reason this works is you are multiplying row 1 times 
# the multiplier you found earlier and adding that to row 2
# to create the new row2
# this is known as E2,1 for the position of the eliminator
EliminateX=np.matrix([
    [1,0,0],
    [-xmultiple,1,0],
    [0,0,1]
])
print(EliminateX)

[[ 1.  0.  0.]
 [-3.  1.  0.]
 [ 0.  0.  1.]]


In [3744]:
A2=EliminateX*Ab
print(A2)

[[ 1.  2.  1.  2.]
 [ 0.  2. -2.  6.]
 [ 0.  4.  1.  2.]]


In [3745]:
# now create E3,2
EliminateY=np.matrix([
    [1,0,0],
    [0,1,0],
    [0,-ymultiple,1]
])
print(EliminateY)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0. -2.  1.]]


In [3746]:
A3=EliminateY*A2
print(A3)

[[  1.   2.   1.   2.]
 [  0.   2.  -2.   6.]
 [  0.   0.   5. -10.]]


In [3747]:
# Lecture 3: Multiplication and inverse matrices
# starts by reviewing an example of Matrix A * B = C
# Then to review that C1,2 equals sumproduct A row 1 times B col 2
# Let's create two simple arrays
A=np.array([
    [1,2],
    [3,4]
])
B=np.array([
    [5,6],
    [7,8]
])
print(A)
print(B)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [3748]:
# Let's manually find C1,1...or for C(a-1),(b-1)
#...since rows and columns start at zero in formulas

a=0 # represents row to multiply for A
b=0 # represents col to multiply for B
y=0 # represents counter for B row
sum=0
for x in A[a]: # will cycle through each num in A row a
    print("sum:",sum)
    print("x is counter of items in A,a:",x)
    print("y is row in B,b:",y)
    print("B[y,b] is item in B:",B[b,y])
    sum+=x*B[y,b] # selected A row num times B row num
    y+=1 #increments the B row
print("final sum:",sum)

sum: 0
x is counter of items in A,a: 1
y is row in B,b: 0
B[y,b] is item in B: 5
sum: 5
x is counter of items in A,a: 2
y is row in B,b: 1
B[y,b] is item in B: 6
final sum: 19


In [3749]:
# to multiply matrices you need to have
# same columns in first as rows in second

In [3750]:
# what happens if you multiply a column times a row
# do you get a full matrix...yes
A=np.matrix([
    [2],
    [3],
    [4]
])
B=np.matrix([
    [1,6]
])
print(A)
print(B)
print(A*B)

[[2]
 [3]
 [4]]
[[1 6]]
[[ 2 12]
 [ 3 18]
 [ 4 24]]


In [3751]:
# What is an inverse?
# If A^(-1)*A=I (Identity matrix)
# Let's start with a non-invertable situation
# That occurs if you can multiply A times something and get zero
A=np.array([
    [1,3],
    [2,6]
])
print(A)
B=np.array([
    [3],
    [-1]
])
print(A*B)

[[1 3]
 [2 6]]
[[ 3  9]
 [-2 -6]]


In [3752]:
# OK let's make an inverse
# Find the inverse of A
A=np.array([
    [1,3],
    [2,7]
])
# Now we set this up equaling the identity...
AI=np.array([
    [1,3,1,0],
    [2,7,0,1]
])
print(AI)

[[1 3 1 0]
 [2 7 0 1]]


In [3753]:
#...Now we eliminate x first

# old code that worked
# A2=np.array([
#     row1,newrow2,row3
# ])
# print (A2)

# find the multiple that you will multiply by
xmultiple=(AI[1,0]/AI[0,0])

# make the rows variable so we can reconstruct the matrix
row1=AI[0]
row2=AI[1]
newrowx=row2-xmultiple*row1
print(newrowx)

# reconstruct the array
newarray=np.matrix([
    row1, newrowx
])
print(newarray)

[ 0.  1. -2.  1.]
[[ 1.  3.  1.  0.]
 [ 0.  1. -2.  1.]]


In [3754]:
# Next we clean out the y up top
ymultiple=newarray[0,1]/newarray[1,1]
print(ymultiple)
newrowy=row1-ymultiple*newrowx
print(newrowy)

3.0
[ 1.  0.  7. -3.]


In [3755]:
# so we have our final matrix
# the right hand side is now the inverse
inverse=np.array([
    newrowy,newrowx
])
print(inverse)

[[ 1.  0.  7. -3.]
 [ 0.  1. -2.  1.]]


In [3756]:
# Lecture 4: Factorization into A=LU
# How do I get the inverse of AB?
# AB(B^-1*A^-1)=I...why?
# Move parentheses and get (B*B^-1) in middle or identity
# So you inverse the order (AB)*BinverseAinverse
# remember you can't just move multipliers around but can move parentheses

In [3757]:
# Also you can transpose the inverse or vice versa

In [3758]:
# an example of A=LU
# start with A

A=np.matrix([
    [2,1],
    [8,7]
])

# -4 will clear out x on bottom
Eliminatex=np.matrix([
    [1,0],
    [-4,1]
])

# Eliminatex*A gives you the following on the other side of equation
# U stands for upper triangle
Upper=np.matrix([
    [2,1],
    [0,3]
])

# you can isolate A by bringing positive 4 to the other side of equation
# L stands for lower triangle
Lower=np.matrix([
    [1,0],
    [4,1]
])

# You can factor U into the following
Ufactor1=np.matrix([
    [2,0],
    [0,3]
])
Ufactor2=np.matrix([
    [1,0.5],
    [0,1]
])

# so now you have A=L*U
# confirm A is the same as beginning
A=Lower*Ufactor1*Ufactor2
print(A)

[[ 2.  1.]
 [ 8.  7.]]


In [3759]:
# factoring a 3x3
# remember first term is eliminate x in 2,1 position, and so on
# E32*E31*E21A=U
# But we just want A on the left, so need inverses on right
# Remember opposite order
# A=(E21^-1)*(E31^-1)*(E32^-1)*U
# Those terms for L, so A=LU

In [3760]:
# What is the processing cost of elimination?
# For nxn rows and cols, you're doing roughly nxn ops to eliminate x from all rows
# This is because each row you're doing something to all nums (multiply then subtract)
# Then you have to eliminate y in the next column, but one row down and so on
# This gives you n^squared + (n-1)^2....1^2
# We know this equation is something less than n^3
# Calculus tells us its 1/3*N^3
# Then you have the b column; processing this turns out to be n^2
# So total cost to process nxn is roughly 1/3N^3+N^2

In [3761]:
# Transposes and permutation
# When a zero shows up in pivot position, need to do row exchanges
# Starting with identity matrix, there are 6 permutations (3x2x1)...which is n! (factorial)
# P123, then P213, then P312, and so on
# Example of P213 below
P=np.array([
    [0,1,0],
    [1,0,0],
    [0,0,1]
])
print(P)

[[0 1 0]
 [1 0 0]
 [0 0 1]]


In [3762]:
# The inverse (P^-1) of a Permutation matrix is the transpose (PT)
# Taking the above, let's find the transpose
Transpose=np.array([
    [P[0,0],P[1,0],P[2,0]],
    [P[1,0],P[1,1],P[1,2]],
    [P[2,0],P[2,1],P[2,2]]
])
print (Transpose)

[[0 1 0]
 [1 0 0]
 [0 0 1]]


In [3763]:
# prove the inverse is the transpose
# multiply one by the other, see if you get identity
Result=np.dot(P,Transpose,out=None)
print(Result)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [3764]:
# Lecture 5: Transposes, permutations, spaces R^n
# Reminder A=LU
# Reminder L has 1s on diagonal, zeros above, numbers below
# Reminder U has 1s on diagonal, zeros below, numbers above
# Then the description with row exchanges is PA=LU...
#....Where P is the permutation
# P=identity matrix with reordered rows

In [3765]:
# Transposes
# for any (AT)ij, it becomes Aji

In [3766]:
# Symmetric matrices
# AT=A - is its own transpose
# Pattern of symmetrical matrix is the diagonals can be anything...
# ...but numbers surrounding them appear twice in a certain order
# Example below
Symmetric=np.array([
    [3,1,7],
    [1,2,9],
    [7,9,4]
])

In [3767]:
# Multiply a matrix times its transpose and its symmetric
# RT*R is always symmetric
# Try it below with the matrix up above, see if it comes out symmetric
Symproduct=np.transpose(A)*A
print(Symproduct)

[[ 68.  58.]
 [ 58.  50.]]


In [3768]:
# Rule for transposes - the order gets reversed and then transpose them
# (RT*R)^T = RT*RTT...double transpose equals the number again, so =RT*R again

In [3769]:
# VECTORS
# Example operations: we need to add vectors, or multiply them (scaling them)
# The vector space allows us to do this
# R^2 means what? Two real numbers...[[3],[2]] for example, or pi and e
# add 2 vectors, just add their components...
# so you would get 3+pi, 2+e for example above
# You can do R^3 for three components/dimensions...[[3],[2],[0]]

In [3770]:
# Defining vector space
# For case of R^2, you want vector space inside R^2
# Picture x and y axis...what are subspaces of R^2
# 1. Could be all of R^2 plane
# 2. Could be any line through origin (could call it L)
# 3. Could be origin - zero vector only (could call it Z)


In [3771]:
# Start with an R3 example
A=np.array([
    [1,3],
    [2,3],
    [4,1]
])
# All their combinations are in the subspace - called column space C(A)
# You get a plane because you have 2 lines (1,2,4) and (3,3,1)...
# and every combination thereof, with the plane going through origin

In [3772]:
# Lecture 6: Column space and nullspace
# Reminder: A vector space is where we can...
#...add or multiply the vectors and stay in the space
# R^3 example: a plane through zero is a subspace of all R^3

In [3773]:
# Suppose you have to subspaces P and L
# is the union (P U L) a subspace? Answer no.
# Why? Because combining elements of each will take you outside the subspace
# Is intersection of P and L a subspace? Yes
# Why? If we take the combination of those vectors they'll stay in that subspace

In [3774]:
# Column space of a matrix
A=np.array([
    [1,1,2],
    [2,1,3],
    [3,1,4],
    [4,1,5]
])
# We are in R^4 now; 
# A is a subspace of R^4
# Column space of A is all linear combination of the columns
# Does this space fill up all the 4 dimensional space? No

In [3775]:
# So when can we solve Ax=b?
# where x is a column of three variables (x1,x2,x3)...
#...and b is a column of four variables (b1,b2,b3)
# Consider that column 3 of A is dependent on first two (sum of both)...
#...Therefore it is not contributing much new

In [3776]:
# What is the nullspace of A?
# It is all solutions to Ax=0 (it is in R^3)
# What are some nullspaces for A above?
# Here is an example:
nulls=np.array([
    [1],
    [1],
    [-1]
])
print(np.dot(A,nulls))
# more generally here, anything with c, c and -c in the x column will generate nullspace
# or else written as c*[[1],[1],[-1]]
# so the nullspace is a line in R^3

[[0]
 [0]
 [0]
 [0]]


In [3777]:
# Lecture 7: Solving Ax=0; Pivot Variables; Special Solutions
A=np.array([
    [1,2,2,2],
    [2,4,6,8],
    [3,6,8,10]
])
# Note that column 2 is not independent (is a multiple of column 1)
# Note that row 3 is not independent (is sum of rows 1 and 2)

In [3778]:
# Reminder - what does elimination do?
# It is like setting the left side equal to zero on the right, we just don't show that
# We manipulate the equations but don't change the solution set or nullspace

In [3779]:
# Let's clear out x for A
Arow1=A[0]
Arow2=A[1]
Arow3=A[2]
xrow2=Arow2-Arow1*(A[1,0]/A[0,0])
xrow3=Arow3-Arow1*(A[2,0]/A[0,0])
A2=np.array([
    Arow1,
    xrow2,
    xrow3
])
print(A2)

[[ 1.  2.  2.  2.]
 [ 0.  0.  2.  4.]
 [ 0.  0.  2.  4.]]


In [3780]:
# Let's clear out z for A (since y is fully zeroed out already)
# oops - row 3 is zeroed out because it was overlapping another
zrow3=xrow3-xrow2*(A2[2,2]/A2[1,2])
U=np.array([
    Arow1,
    xrow2,
    zrow3
])
print(U)

[[ 1.  2.  2.  2.]
 [ 0.  0.  2.  4.]
 [ 0.  0.  0.  0.]]


In [3781]:
#U above has 2 pivots; that number is called the rank
# the others are "free variables"; so you have 2 pivots and 2 free
# Let's solve for Ux=0
# create a column of x's and fill in a one and a zero in the free variable columns
# A solution for the above is 
x=np.array([
    [-2],
    [1],
    [0],
    [0]
])
# But you could also do a multiple of this, so any c*x above
print(np.dot(U,x))

[[ 0.]
 [ 0.]
 [ 0.]]


In [3782]:
# Let's generalize the approach
# use a 1 and a 0 for the free variables, then solve for pivots
# try the opposite combo of 0 and 1 as above and what works
x2=np.array([
    [2],
    [0],
    [-2],
    [1]
])
print(np.dot(U,x2))

[[ 0.]
 [ 0.]
 [ 0.]]


In [3783]:
# we didn't fully reduce U to R
# R is reduced echelon form where pivots are zero
# get a zero above the z in row 1, and a 1 in the pivot for row 2

zrow1=Arow1-xrow2
zrow2=0.5*xrow2
R=np.array([
    zrow1,
    zrow2,
    zrow3
])
print(R)

# Note matlab will find R with command rref (reduced row echelon form)
# see how R has identity matrix for the pivot rows/cols [[1,0],[0,1]]

[[ 1.  2.  0. -2.]
 [ 0.  0.  1.  2.]
 [ 0.  0.  0.  0.]]


In [3784]:
# note the connection in the free cols above with the solutions prior
# so you have 2 and 0 in one column; -2 and 2 in another
# this is like what you found earlier to solve for Ux=0, EXCEPT...
# signs are opposite because they are on other side of equation

In [3785]:
# what if you had R
#R=np.array([
#    [I,F],
#    [0,0]
#])
# find RN=0; nullspace matrix
# N=[[-F],[I]]

In [3786]:
# Take transpose of earlier matrix
A=np.array([
    [1,2,3],
    [2,4,6],
    [2,6,8],
    [2,8,10]
])
# We can see straight away this will have two pivot columns and one free
# This is because third column is dependent (is sum of cols 1 and 2)

In [3787]:
# Lecture 8: Solving Ax=b
# Ax=b is solvable when b is in the column space of A (also written C(A))
# If a combination of the rows of A gives a zero row...
# The same combination of the entries of B must give zero

In [3788]:
# To find the complete solution to Ax=B...
# Let's start with a single one
# Step 1. set all free variables to zero
# Step 2. solve Ax=b for the pivot variables
# This lus the nullspace gives you the complete solution

In [3789]:
# m by n matrix A of rank r 
# we know (r<=m and r<=n)
# What if your columns equal rank r=n, so no free variables
# In this case, null space N(A) is only the zero vector (no free vars to give values to)
# solution Ax=b is then just x particular (if it exists)
# So only zero or one solutions (because may not exist)

In [3790]:
# Example with full column rank
A=np.array([
    [1,3],
    [2,1],
    [6,1],
    [5,1]
])
# If right hand side was 4,3,7,6 you would have one solution (x and y both = 1) 

In [3791]:
# Let's try an example with full row rank
# Full row rank means r=m
# In this case, can always solve Ax=b for every b
# You may have free variables...left with n-r free variables
# As an example, let's transpose the matrix above
A=np.array([
    [1,2,6,5],
    [3,1,1,1]
])
# So the rank is 2; free vars are n-2 or 4-2 or 2
# What will R (reduced row echelon) look like for this?
# will have identity matrix on left 2 columns, the some F will be the right two
# So you will have some null space here based on F

In [3792]:
# what if you have a square where r=m=n
# R=I
# No mull space (zero vector only)
# For [square matrix]=[column of b's], there is a unique solution

In [3793]:
# So generalizing now:
# For square r=m=n, R=I, 1 solution for Ax=b
# For more rows than columns w/full column rank, r=n<m, R=[[I],[0]], zero or one solution for Ax=b
# For more columns than rows w/full row rank r=m<n, R=[I F]...
#...infinite solutions since always some null space
# Then where r<m and r<n, R=[[I F], [0, 0]], zero or infinity solutions
# So in conclusion, the rank tells you everything about the number of solutions


In [3794]:
# Lecture 9: Independence, basis and dimension
# Suppose A is m by n with m<n...
#...Then there will be nonzero solutions to Ax=o (more unknowns than equations)
# Separately, Vectors x1, x2, x3, etc. are independent if no combination gives zero vector
# If we have m<n, we will have some dependent (some combination gives zero vector)

In [3795]:
# Example - drawing vectors on a 2 dimensional plane
A=np.array([
    [2,1,2.5],
    [1,2,-1]
])
# Note that the vectors are the columns...
# So V1 vector one is 2,1
# V2 vector two is 1,2
# V3 is 2,-1

In [3796]:
# Repeat when v1, ...vn are columns of A...
# They are independent if nullspace of A is only the zero vector
# They are dependent if there's something else in there
# So independent is when rank=number of columns (no free variables)
# Depdendent is when rank<number of columns (you have free variables)

In [3797]:
# What does it mean for a bunch of vectors to span (S) a space?
# So vectors v1....vL span a space means...
#...the space consists of all combinations of those vectors

In [3798]:
# Basis for a vector space is a sequence of vectors v1, v2...vd...
#...with two properties: They are independent and span the space

In [3799]:
# Example. Space is R3...
# One basis is the identity matrix
# Another example:
A=np.array([
    [1,2,3],
    [2,2,3],
    [3,5,8]
])

In [3800]:
# On my own - want to test the numpy solution for linear equations
# Found formula which is numpy.linalg.solve (a,b)...
# ...where a is the matrix of coefficients
#...and b is the dependent variable column on the right
# Let's try array above but add some b's to the end
print("A is ",A)
B=np.array([
    [2],
    [9],
    [50]
])
print("B is ",B)
C=np.linalg.solve(A,B)
print("Solution for x y z is",C)

A is  [[1 2 3]
 [2 2 3]
 [3 5 8]]
B is  [[ 2]
 [ 9]
 [50]]
Solution for x y z is [[   7.]
 [-127.]
 [  83.]]


In [3801]:
# Rn vectors give basis for the nxn matris with these columns is invertible
# Every basis for the space has the same number of vector...
# This number is the DIMENSION of the space

In [3802]:
# Example where column space of A is C(A)
# Think the idea here is first three columns are like the coefficients of variables
A=np.array([
    [1,2,3,1],
    [1,1,2,1],
    [1,2,3,1]
])
# Since third column is sum of first two, an example of the null solution is
N1=np.array([
    [-1],
    [-1],
    [1],
    [0]
])
print (np.dot(A,N1))
N2=np.array([
    [-1],
    [0],
    [0],
    [1]
])
print(np.dot(A,N2))

[[0]
 [0]
 [0]]
[[0]
 [0]
 [0]]


In [3803]:
# Continuing with the example, the rank is 2...
# rank(A)= number of pivot columns = the dimension of its column space C(A)
# And the basis is well any number of possibilities within the column space
# Once basis for C(A) here is 7,5,7 (the sum of the columns)
# The dimension of the null space is the number of free variables
# We know n-r=free variables which is dimension of the null space

In [ ]:
# Four sub-spaces, where A is mxn
# columnspace C(A) - is in R^m
# nullspace N(A) - is R^n
# rowspace - all combinations of rows - we like using col vectors better...
# so this also equals all combs of columns of A transpose (A^T)
# null space of A transpose N(A^T), or the "left nullspace"